Add pIC50 uncertainties in schema objects
choderalab/covid-moonshot-ml pull request #11
Opened 2022-07-27 18:43 UTC by kaminow

Updated the CDD parsing functions to calculate and store the variance in the pIC50 measurement.

2022-08-09 02:49 UTC, jchodera requested changes
Apologies for not seeing this earlier!
Suggest changing variance -> standard error, but otherwise this looks great!

2022-08-09 02:49 UTC, jchodera commented on covid_moonshot_ml/datasets/utils.py
> +            pic50_var.append(((pic50_ci_lower - pic50_ci_upper) / 4) ** 2)
Suggest storing the `stderr` (standard error) is better than the `var` (variance).

2022-08-09 02:50 UTC, jchodera commented
Also, I'm not sure if you're storing the semiquantitative data yet, but if you are, then you can set the standard error to a default value (e.g. 0.5 pIC50 units) if there is no confidence interval defined.

2022-08-09 14:34 UTC, kaminow commented
> Also, I'm not sure if you're storing the semiquantitative data yet, but if you are, then you can set the standard error to a default value (e.g. 0.5 pIC50 units) if there is no confidence interval defined.

Should this be handled when parsing the data or should the value be left up to the user at train/test time? Currently I'm storing NaNs where there is no CI info, but I can change that to 0.5 or whatever value we want. I am storing semiquantitative data: https://github.com/choderalab/covid-moonshot-ml/blob/add-uncertainties/covid_moonshot_ml/datasets/utils.py#L216-L217
so this can be used as well

2022-08-11 02:16 UTC, jchodera commented
> Should this be handled when parsing the data or should the value be left up to the user at train/test time?
> Currently I'm storing NaNs where there is no CI info, but I can change that to 0.5 or whatever value we want.

Good question!

For preparing CSV files for redistribution, it would be best to pre-populate the uncertainty with a sensible value that reflects an appropriate uncertainty for the limits here, which may be tighter than 0.5 pIC50 units.

For use in your ML models, it may makes the most sense to enable you to interpret the NaNs and experiment with different uncertainties for the semiquantiative data.

2022-08-11 15:43 UTC, kaminow commented
@jchodera I've updated the code to now fill the standard error for any compounds outside the dynamic range of the fluorescence assay with the mean of the compounds that _are_ within the dynamic range. The compounds still keep track of whether the pIC50 value was above, within, or below the dynamic range, so it's trivial to update the default value.

2022-08-15 05:13 UTC, jchodera commented
That sounds like a decent approach! It looks like you just need to rebase or merge in `main` and then we can merge!

2022-08-18 00:23 UTC, jchodera approved these changes

2022-08-18 00:23 UTC, jchodera approved these changes
Looks good, thanks!

2022-08-25 14:57 UTC, ijpulidos commented
Closing this PR in order to avoid unintended side effects when removing the data from git and github history.

2022-08-25 14:57 UTC, closed without merging